### ISSUE TITLE
HLA result

### ISSUE THREAD

**Issue by uso2015** [PacificBiosciences/hifihla#5]
Hi，

      there are two questions when I use HiFihla software.
       1、why the HLA-A_1 is "HLA-A*11:01:01" not "HLA-A*11:01:01:55"? (final column)
       2、why the HLA-B_0 is "HLA-B" not "HLA-B*52:01:01:02"? (final column)

![HLA](https://github.com/PacificBiosciences/hifihla/assets/16254381/9405d51f-ef95-4b6c-b53f-ba42ecb41742)

**Comment by jrharting** [comment]
1.  There are 2 equivalent matches at 99.93% of bases covered for the 2 reads in this cluster, and thus the exact match is ambiguous for these two reads.  This is probably a case where the locus is homozygous and the extra call is a spurious cluster.   you can adjust the min cdf to help remove this extra call.
2.  Probably a similar case where the locus is homozygous and its generating a spurious cluster based on read error.  Any match that has coding diffs (exEdit > 0) is not given a final type call.

Given that  locus C also looks homozygous you can also set `--haplotypes 1` and it won't try to cluster.
